language: java
jdk:
  - openjdk11

sudo: required

before_install:
 - chmod +x gradlew
 
script:
 - ./gradlew build
  
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  on: main
  app: "bookstore-service"