language: java
jdk:
  - openjdk11

sudo: required

before_install:
 - chmod +x gradlew
 
script:
 - ./gradlew build
  
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  on: main
  app: "bookstore-service"